// Testbench for binarize_core.
// Loads tb_gray.bin and tb_bin_golden.bin generated by
// binarize_generate_golden.py, streams through the HLS function,
// and checks pixel agreement vs the OpenCV reference.

#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <cassert>
#include "binarize_core.h"

// Tolerate up to 0.1% pixel mismatch (border artefacts from different
// padding behaviour between HLS LineBuffer and cv2.GaussianBlur).
static const double MAX_MISMATCH_RATIO = 0.001;

int main()
{
    // ---- Load parameters ------------------------------------------------
    FILE* fp = fopen("tb_binarize_params.txt", "r");
    if (!fp) { fprintf(stderr, "Run binarize_generate_golden.py first.\n"); return 1; }
    int threshold, iw, ih;
    fscanf(fp, "%d %d %d", &threshold, &iw, &ih);
    fclose(fp);
    printf("Image: %d×%d  threshold: %d\n", iw, ih, threshold);

    int total = iw * ih;
    unsigned char* gray_buf   = new unsigned char[total];
    unsigned char* golden_buf = new unsigned char[total];
    unsigned char* dut_buf    = new unsigned char[total];

    // ---- Load input and golden ------------------------------------------
    auto read_bin = [](const char* path, unsigned char* buf, int n) {
        FILE* f = fopen(path, "rb");
        if (!f) { fprintf(stderr, "Cannot open %s\n", path); exit(1); }
        fread(buf, 1, n, f);
        fclose(f);
    };
    read_bin("tb_gray.bin",       gray_buf,   total);
    read_bin("tb_bin_golden.bin", golden_buf, total);

    // ---- Build streams --------------------------------------------------
    hls::stream<bpix_t> gray_stream("gray");
    hls::stream<bpix_t> bin_stream("bin");

    for (int i = 0; i < total; i++) {
        bpix_t px;
        px.data = gray_buf[i];
        px.last = (i == total-1) ? 1 : 0;
        px.keep = 0xFF;
        gray_stream.write(px);
    }

    // ---- Run DUT --------------------------------------------------------
    binarize_core(gray_stream, bin_stream,
                  (ap_uint<16>)iw, (ap_uint<16>)ih,
                  (ap_uint<8>)threshold);

    for (int i = 0; i < total; i++) {
        bpix_t px = bin_stream.read();
        dut_buf[i] = px.data;
    }

    // ---- Compare --------------------------------------------------------
    int mismatches = 0;
    for (int i = 0; i < total; i++) {
        if (dut_buf[i] != golden_buf[i]) mismatches++;
    }
    double ratio = (double)mismatches / total;
    printf("Mismatched pixels: %d / %d  (%.4f%%)\n",
           mismatches, total, ratio * 100.0);

    delete[] gray_buf;
    delete[] golden_buf;
    delete[] dut_buf;

    if (ratio > MAX_MISMATCH_RATIO) {
        fprintf(stderr, "TESTBENCH FAILED: mismatch %.4f%% > %.4f%%\n",
                ratio * 100.0, MAX_MISMATCH_RATIO * 100.0);
        return 1;
    }
    printf("TESTBENCH PASSED\n");
    return 0;
}
